name: Continuous Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy Retroyrd Container
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Rebuild and Restart Docker Container
        run: |
          cd /opt/retroyrd
          git pull origin main
          docker compose build
          docker compose up -d
